global using System;
global using System.IO;
global using System.Text;
global using System.Linq;
global using System.Collections.Generic;
global using BitcoinBlockchainParser.Extensions;
global using BitcoinBlockchainParser.Crypto;
global using BitcoinBlockchainParser.Streams;
global using BitcoinBlockchainParser.DataTypes;